"""Add ON DELETE CASCADE to tareas.user_id

Revision ID: 3e3ec05a8638
Revises: a6bab4404411
Create Date: 2025-07-11 10:05:02.526470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3ec05a8638'
down_revision: Union[str, None] = 'a6bab4404411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    with op.batch_alter_table("tareas", recreate="always") as batch_op:
        batch_op.create_foreign_key(
            'tareas_user_id_fkey',
            'users',
            ['user_id'],
            ['id'],
            ondelete='CASCADE'
        )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'tareas', type_='foreignkey')
    op.create_foreign_key(op.f('tareas_user_id_fkey'), 'tareas', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
